name: Release

on:
  pull_request_target:
    types:
      - closed
    branches:
      - 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          
      # DOWNLOAD BUILD ARTIFACTS.
      - name: Download artifacts from Windows builds
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: ${{ github.event.pull_request.head.ref }}
          workflow_search: false
          workflow_conclusion: success
          name: TotkArmorTracker_Windows

      - name: Download artifacts from Linux builds
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: ${{ github.event.pull_request.head.ref }}
          workflow_search: false
          workflow_conclusion: success
          name: TotkArmorTracker_Linux
          
      - name: Download artifacts from Windows builds
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          branch: ${{ github.event.pull_request.head.ref }}
          workflow_search: false
          workflow_conclusion: success
          name: TotkArmorTracker_Windows

      # GENERATE NEW GITHUB RELEASE.
      - name: Create new release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          release_name: Release ${{ github.event.pull_request.head.ref }}
          draft: false
          prerelease: false

      # ATTACH APPLICATION BUNDLES TO NEW RELEASE.
      - name: Upload Windows Bundle
        id: upload_windows_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TotkArmorTracker_Windows.zip
          asset_name: TotkArmorTracker_Windows.zip
          asset_content_type: application/zip

      - name: Upload Linux Bundle
        id: upload_linux_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TotkArmorTracker_Linux.zip
          asset_name: TotkArmorTracker_Linux.zip
          asset_content_type: application/zip

      - name: Upload MacOS Bundle
        id: upload_macos_release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: TotkArmorTracker_MacOS.zip
          asset_name: TotkArmorTracker_MacOS.zip
          asset_content_type: application/zip
